#!/usr/bin/env python3
"""Taichi benchmark test harness generation.

CLI:
    python3 evo_taichi_harness.py --harness --file F --function FN [--target-ms 12.0] [--template generic]
"""

import argparse
import sys
from gk_log import gk_error, gk_warn
from evo_taichi_analyze import analyze_internal


def cmd_harness(args):
    """Generate a pytest benchmark test file for a Taichi kernel."""
    file_path = args.file
    function_name = args.function
    target_ms = args.target_ms
    template = args.template

    analysis = analyze_internal(file_path, function_name)
    if analysis is None:
        sys.exit(1)

    if template == "generic":
        output = _generate_generic_harness(analysis, target_ms)
    else:
        gk_warn(f"Unknown template '{template}', falling back to 'generic'")
        output = _generate_generic_harness(analysis, target_ms)

    print(output)


def _generate_param_comments(parameters, indent=""):
    """Generate parameter documentation comments."""
    lines = []
    for p in parameters:
        tpl = " (TEMPLATE)" if p["is_template"] else ""
        lines.append(f"{indent}#   {p['name']}: {p['type']}{tpl}")
    return "\n".join(lines)


def _generate_generic_harness(analysis, target_ms):
    """Generate a minimal benchmark test with ti.init() and basic fields."""
    fn = analysis["function_name"]
    file_path = analysis["file_path"]
    params = analysis["parameters"]
    loc = analysis["loc"]
    thread_range = analysis["thread_range"] or "unknown"
    fields = analysis["field_refs"]

    param_comments_doc = _generate_param_comments(params)
    param_comments_code = _generate_param_comments(params, indent="    ")
    fields_str = ", ".join(fields) if fields else "none detected"

    target_doc = ""
    if target_ms is not None:
        target_doc = f"\nTarget: <{target_ms}ms"

    lines = []
    lines.append(f'"""Auto-generated benchmark for {fn}.')
    lines.append(f"")
    lines.append(f"Generated by evo_taichi_harness.py (generic template)")
    lines.append(f"Source: {file_path}")
    lines.append(f"Kernel LOC: {loc}")
    lines.append(f"Thread range: {thread_range}{target_doc}")
    lines.append(f"")
    lines.append(f"Parameters:")
    lines.append(param_comments_doc)
    lines.append(f"")
    lines.append(f"Field refs: {fields_str}")
    lines.append(f'"""')
    lines.append(f"import time")
    lines.append(f"import pytest")
    lines.append(f"")
    lines.append(f"")
    lines.append(f'@pytest.fixture(scope="module")')
    lines.append(f"def ti_setup():")
    lines.append(f'    """Minimal Taichi setup for benchmarking."""')
    lines.append(f"    import taichi as ti")
    lines.append(f"    ti.init(arch=ti.gpu, offline_cache=True)")
    lines.append(f"")
    lines.append(f"    # TODO: Create fields and state needed by {fn}")
    lines.append(f"    # Example:")
    lines.append(f"    #   field_a = ti.field(dtype=ti.f32, shape=(256, 256))")
    lines.append(f"    #   field_b = ti.Vector.field(3, dtype=ti.f32, shape=(256, 256))")
    lines.append(f"")
    lines.append(f'    yield {{')
    lines.append(f'        "ti": ti,')
    lines.append(f'    }}')
    lines.append(f"")
    lines.append(f"")
    lines.append(f"@pytest.mark.perf")
    lines.append(f"def test_{fn}_timing(ti_setup):")
    lines.append(f'    """Benchmark {fn}."""')
    lines.append(f"    import taichi as ti")
    lines.append(f"")
    lines.append(f"    # TODO: Import the kernel and build args")
    lines.append(f"    # Kernel signature:")
    lines.append(param_comments_code)
    lines.append(f"    raise NotImplementedError(")
    lines.append(f'        "Fill in kernel import and argument construction for {fn}"')
    lines.append(f"    )")
    lines.append(f"")
    lines.append(f"    # ---- Warmup (JIT compile) ----")
    lines.append(f"    for _ in range(3):")
    lines.append(f"        {fn}(*args)")
    lines.append(f"        ti.sync()")
    lines.append(f"")
    lines.append(f"    # ---- Timed trials ----")
    lines.append(f"    timings = []")
    lines.append(f"    for _ in range(10):")
    lines.append(f"        ti.sync()")
    lines.append(f"        t0 = time.perf_counter()")
    lines.append(f"        {fn}(*args)")
    lines.append(f"        ti.sync()")
    lines.append(f"        elapsed_ms = (time.perf_counter() - t0) * 1000")
    lines.append(f"        timings.append(elapsed_ms)")
    lines.append(f"")
    lines.append(f"    timings.sort()")
    lines.append(f"    median_ms = timings[len(timings) // 2]")
    lines.append(f"    min_ms = timings[0]")
    lines.append(f"    max_ms = timings[-1]")
    lines.append(f"")
    lines.append("    print(f\"\\n{'=' * 50}\")")
    lines.append(f'    print(f"{fn} benchmark")')
    lines.append(f'    print(f"  Median: {{median_ms:.2f}}ms")')
    lines.append(f'    print(f"  Min:    {{min_ms:.2f}}ms")')
    lines.append(f'    print(f"  Max:    {{max_ms:.2f}}ms")')
    if target_ms is not None:
        lines.append(f'    print(f"  Target: <{target_ms}ms")')
    lines.append("    print(f\"{'=' * 50}\")")

    if target_ms is not None:
        lines.append(f"")
        lines.append(f"    # Timing assertion")
        lines.append(f"    assert median_ms < {target_ms}, \\")
        lines.append(f'        f"{fn} took {{median_ms:.1f}}ms, target <{target_ms}ms"')

    lines.append(f"")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Taichi benchmark harness generation")
    parser.add_argument("--harness", action="store_true", required=True)
    parser.add_argument("--file", required=True, help="Python file containing the kernel")
    parser.add_argument("--function", required=True, help="Function name to benchmark")
    parser.add_argument("--target-ms", type=float, default=None, help="Target timing in ms")
    parser.add_argument("--template", type=str, default="generic", choices=["generic"])
    args = parser.parse_args()
    cmd_harness(args)


if __name__ == "__main__":
    main()
