#!/bin/bash

# Verifier-Gated Loop Setup Script (GSD-VGL)
#
# SECURITY MODEL:
# 1. Completion token is stored in a SEPARATE file (.claude/verifier-token.secret)
# 2. The Verifier subagent prompt does NOT contain the token
# 3. To get the token, Verifier must call fetch-completion-token.sh
# 4. That script runs tests INDEPENDENTLY and only reveals token if they pass
# 5. Even if the Verifier lies about verification, it can't get the token without passing tests
# 6. Verifier prompt is generated by generate-verifier-prompt.sh (immutable to executor)

set -euo pipefail

PLUGIN_ROOT="$(dirname "$(dirname "$(realpath "$0")")")"

# Check if JSON input is provided via --from-json
if [[ "${1:-}" == "--from-json" ]]; then
  JSON_INPUT="${2:-}"
  if [[ -z "$JSON_INPUT" ]]; then
    echo "Error: --from-json requires JSON string" >&2
    exit 1
  fi

  PARSE_ERROR=$(echo "$JSON_INPUT" | jq -r '.error // empty' 2>/dev/null)
  if [[ -n "$PARSE_ERROR" ]]; then
    echo "Error: $PARSE_ERROR" >&2
    exit 1
  fi

  PROMPT=$(echo "$JSON_INPUT" | jq -r '.prompt')
  VERIFICATION_CRITERIA=$(echo "$JSON_INPUT" | jq -r '.verification_criteria')
  TEST_COMMAND=$(echo "$JSON_INPUT" | jq -r '.test_command')
  VERIFIER_MODEL=$(echo "$JSON_INPUT" | jq -r '.verifier_model // "opus"')
  MAX_ITERATIONS=$(echo "$JSON_INPUT" | jq -r '.max_iterations // 0')
  PLAN_MODE=$(echo "$JSON_INPUT" | jq -r '.plan_mode // false')
  TASK_ID=$(echo "$JSON_INPUT" | jq -r '.task_id // ""')
  TASK_JSON=$(echo "$JSON_INPUT" | jq -r '.task_json // ""')
  TASK_PROMPT_CONTENT=$(echo "$JSON_INPUT" | jq -r '.task_prompt_content // ""')
  SESSION_DIR=$(echo "$JSON_INPUT" | jq -r '.session_dir // ".claude"')

  if [[ -z "$PROMPT" ]] || [[ "$PROMPT" == "null" ]]; then
    echo "Error: No prompt provided" >&2
    exit 1
  fi

  if [[ -z "$VERIFICATION_CRITERIA" ]] || [[ "$VERIFICATION_CRITERIA" == "null" ]]; then
    echo "Error: --verification-criteria is required" >&2
    exit 1
  fi
else
  # Legacy: parse arguments directly from positional params
  PROMPT_PARTS=()
  MAX_ITERATIONS=0
  VERIFICATION_CRITERIA=""
  TEST_COMMAND=""
  VERIFIER_MODEL="opus"
  PLAN_MODE="false"
  TASK_ID=""
  TASK_JSON=""
  TASK_PROMPT_CONTENT=""
  SESSION_DIR=".claude"

  while [[ $# -gt 0 ]]; do
    case $1 in
      -h|--help)
        cat << 'HELP_EOF'
GSD-VGL - Verifier-Gated Loop with TDD + opencode MCP

USAGE:
  /bridge [PROMPT...] [OPTIONS]

ARGUMENTS:
  PROMPT...    Task description (can be multiple words)

OPTIONS:
  --verification-criteria '<text>'  What the Verifier checks (REQUIRED)
  --test-command '<cmd>'            Command to run tests (default: auto-detect)
  --verifier-model <model>          Model for Verifier (default: opus)
  --max-iterations <n>              Max iterations (default: unlimited)
  -h, --help                        Show this help

SECURITY MODEL:
  The completion token is NEVER given to the Verifier upfront.

  Instead:
  1. Verifier does its quality checks (reads code, looks for issues)
  2. When Verifier thinks everything is good, it calls fetch-completion-token.sh
  3. That script runs tests INDEPENDENTLY
  4. Token is ONLY revealed if tests pass

HELP_EOF
        exit 0
        ;;
      --max-iterations)
        if [[ -z "${2:-}" ]] || ! [[ "$2" =~ ^[0-9]+$ ]]; then
          echo "Error: --max-iterations requires a positive integer" >&2
          exit 1
        fi
        MAX_ITERATIONS="$2"
        shift 2
        ;;
      --verification-criteria)
        if [[ -z "${2:-}" ]]; then
          echo "Error: --verification-criteria requires text argument" >&2
          exit 1
        fi
        VERIFICATION_CRITERIA="$2"
        shift 2
        ;;
      --test-command)
        if [[ -z "${2:-}" ]]; then
          echo "Error: --test-command requires a command" >&2
          exit 1
        fi
        TEST_COMMAND="$2"
        shift 2
        ;;
      --verifier-model)
        if [[ -z "${2:-}" ]]; then
          echo "Error: --verifier-model requires a model name" >&2
          exit 1
        fi
        VERIFIER_MODEL="$2"
        shift 2
        ;;
      *)
        PROMPT_PARTS+=("$1")
        shift
        ;;
    esac
  done

  PROMPT="${PROMPT_PARTS[*]}"

  if [[ -z "$PROMPT" ]]; then
    echo "Error: No prompt provided" >&2
    exit 1
  fi

  if [[ -z "$VERIFICATION_CRITERIA" ]]; then
    echo "Error: --verification-criteria is required" >&2
    exit 1
  fi
fi

# Auto-detect test command
if [[ -z "$TEST_COMMAND" ]]; then
  if [[ -f "pyproject.toml" ]] || [[ -f "pytest.ini" ]]; then
    TEST_COMMAND="pytest"
  elif [[ -f "vitest.config.ts" ]] || [[ -f "vitest.config.js" ]]; then
    TEST_COMMAND="bunx vitest run"
  elif [[ -f "package.json" ]]; then
    TEST_COMMAND="npm test"
  else
    TEST_COMMAND="pytest"
  fi
  echo "Auto-detected test command: $TEST_COMMAND"
fi

# Generate cryptographic completion token (128-bit)
COMPLETION_TOKEN="VGL_COMPLETE_$(openssl rand -hex 16 2>/dev/null || head -c 32 /dev/urandom | xxd -p | tr -d '\n')"
SESSION_ID="vgl_$(date +%s)_$(openssl rand -hex 4 2>/dev/null || head -c 8 /dev/urandom | xxd -p | tr -d '\n')"

# Create state directory
mkdir -p "$SESSION_DIR"

# Store token AND test command in SECRET FILE (tamper-proof)
TEST_CMD_B64=$(echo -n "$TEST_COMMAND" | base64 -w0)
TEST_CMD_HASH=$(echo -n "$TEST_COMMAND" | sha256sum | cut -d' ' -f1)
cat > "${SESSION_DIR}/verifier-token.secret" <<SECRETEOF
$COMPLETION_TOKEN
TEST_CMD_B64:$TEST_CMD_B64
TEST_CMD_HASH:$TEST_CMD_HASH
SECRETEOF
chmod 600 "${SESSION_DIR}/verifier-token.secret" 2>/dev/null || true

# Create state file
PLAN_MODE_FRONTMATTER=""
if [[ "$PLAN_MODE" == "true" ]] && [[ -n "$TASK_ID" ]]; then
  PLAN_MODE_FRONTMATTER="plan_mode: true
task_id: \"$TASK_ID\""
fi

cat > "${SESSION_DIR}/verifier-loop.local.md" <<EOF
---
active: true
session_id: "$SESSION_ID"
iteration: 1
max_iterations: $MAX_ITERATIONS
verification_criteria: |
$(echo "$VERIFICATION_CRITERIA" | sed 's/^/  /')
test_command: "$TEST_COMMAND"
verifier_model: "$VERIFIER_MODEL"
project_dir: "$(pwd)"
started_at: "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
$PLAN_MODE_FRONTMATTER
---

$PROMPT
EOF

# Resolve absolute paths at setup time (subagents don't have CLAUDE_PLUGIN_ROOT)
FETCH_SCRIPT="$PLUGIN_ROOT/scripts/fetch-completion-token.sh"
PROJECT_DIR="$(pwd)"

# Create Verifier prompt — plan mode uses generate-verifier-prompt.sh
if [[ "$PLAN_MODE" == "true" ]] && [[ -n "$TASK_JSON" ]]; then
  PLAN_FILE=".claude/plan/plan.yaml"

  # Use generate-verifier-prompt.sh for immutable prompt generation
  GEN_ARGS=(
    --task-json "$TASK_JSON"
    --fetch-script "$FETCH_SCRIPT"
    --session-dir "$SESSION_DIR"
    --project-dir "$PROJECT_DIR"
  )
  if [[ -f "$PLAN_FILE" ]]; then
    GEN_ARGS+=(--plan-file "$PLAN_FILE")
  fi
  if [[ -n "$TASK_PROMPT_CONTENT" ]]; then
    GEN_ARGS+=(--task-prompt-content "$TASK_PROMPT_CONTENT")
  fi

  bash "${PLUGIN_ROOT}/scripts/generate-verifier-prompt.sh" "${GEN_ARGS[@]}"

else
  # Standard (non-plan) verifier prompt
  cat > "${SESSION_DIR}/verifier-prompt.local.md" <<EOF
You are a VERIFICATION AGENT.

CRITERIA: $VERIFICATION_CRITERIA

STEPS - follow exactly in order:
1. Read source files in $PROJECT_DIR/
2. Run: cd $PROJECT_DIR && $TEST_COMMAND
3. If tests pass, run: cd $PROJECT_DIR && bash $FETCH_SCRIPT --session-dir ${SESSION_DIR}

OUTPUT FORMAT - your entire text response must be exactly one of these two formats:

If the fetch script grants a token:
<verification-complete>
PASS: [paste the token from the fetch script here]
</verification-complete>

If tests fail or the fetch script denies:
<verification-complete>
FAIL
</verification-complete>

Say nothing else. Your entire response is one of those two blocks. No commentary, no explanation, no analysis.
EOF
fi

# Output setup message
cat <<EOF

╔═══════════════════════════════════════════════════════════════════════════════════════╗
║                     GSD-VGL: VERIFIER-GATED LOOP ACTIVATED                           ║
╠═══════════════════════════════════════════════════════════════════════════════════════╣
║                                                                                       ║
║  Session:              $SESSION_ID
║  Iteration:            1
║  Max iterations:       $(printf "%-10s" "$(if [[ $MAX_ITERATIONS -gt 0 ]]; then echo $MAX_ITERATIONS; else echo "unlimited"; fi)")
║  Test command:         $TEST_COMMAND
║  Verifier model:       $VERIFIER_MODEL
║                                                                                       ║
╠═══════════════════════════════════════════════════════════════════════════════════════╣
║  SECURITY: Token in ${SESSION_DIR}/verifier-token.secret (protected)                  ║
║  Verifier must call fetch-completion-token.sh — tests run independently               ║
╚═══════════════════════════════════════════════════════════════════════════════════════╝

EOF

echo "$PROMPT"
echo ""
echo "═══════════════════════════════════════════════════════════════════════════════════════"
echo "BEGIN WORK — TDD-first: write tests, spawn opencode agents, then verify"
echo "═══════════════════════════════════════════════════════════════════════════════════════"
