#!/bin/bash

# Verifier-Gated Loop Setup Script (GSD-VGL)
#
# SECURITY MODEL:
# 1. Completion token is stored in a SEPARATE file (.claude/verifier-token.secret)
# 2. The Verifier subagent prompt does NOT contain the token
# 3. To get the token, Verifier must call fetch-completion-token.sh
# 4. That script runs tests INDEPENDENTLY and only reveals token if they pass
# 5. Even if the Verifier lies about verification, it can't get the token without passing tests
# 6. Verifier prompt is generated by generate-verifier-prompt.sh (immutable to executor)

set -euo pipefail

PLUGIN_ROOT="$(dirname "$(dirname "$(realpath "$0")")")"

# Deploy gsd-builder agent config if not already present
OPENCODE_CONFIG="opencode.json"
if [[ ! -f "$OPENCODE_CONFIG" ]] || ! python3 -c "
import json
with open('$OPENCODE_CONFIG') as f:
    cfg = json.load(f)
raise SystemExit(0 if 'gsd-builder' in cfg.get('agent', {}) else 1)
" 2>/dev/null; then
  cp "${PLUGIN_ROOT}/templates/opencode.json" "$OPENCODE_CONFIG"
  echo "Deployed gsd-builder agent config"
fi

# Check if JSON input is provided via --from-json
if [[ "${1:-}" == "--from-json" ]]; then
  JSON_INPUT="${2:-}"
  if [[ -z "$JSON_INPUT" ]]; then
    echo "Error: --from-json requires JSON string" >&2
    echo "Try: Provide a valid JSON string as the second argument to --from-json." >&2
    exit 1
  fi

  PARSE_ERROR=$(echo "$JSON_INPUT" | jq -r '.error // empty' 2>/dev/null)
  if [[ -n "$PARSE_ERROR" ]]; then
    echo "Error: $PARSE_ERROR" >&2
    echo "Try: Check the JSON input for syntax errors." >&2
    exit 1
  fi

  PROMPT=$(echo "$JSON_INPUT" | jq -r '.prompt')
  VERIFICATION_CRITERIA=$(echo "$JSON_INPUT" | jq -r '.verification_criteria')
  TEST_COMMAND=$(echo "$JSON_INPUT" | jq -r '.test_command')
  VERIFIER_MODEL=$(echo "$JSON_INPUT" | jq -r '.verifier_model // "opus"')
  MAX_ITERATIONS=$(echo "$JSON_INPUT" | jq -r '.max_iterations // 0')
  PLAN_MODE=$(echo "$JSON_INPUT" | jq -r '.plan_mode // false')
  TASK_ID=$(echo "$JSON_INPUT" | jq -r '.task_id // ""')
  TASK_JSON=$(echo "$JSON_INPUT" | jq -r '.task_json // ""')
  TASK_PROMPT_CONTENT=$(echo "$JSON_INPUT" | jq -r '.task_prompt_content // ""')
  SESSION_DIR=$(echo "$JSON_INPUT" | jq -r '.session_dir // ".claude"')

  if [[ -z "$PROMPT" ]] || [[ "$PROMPT" == "null" ]]; then
    echo "Error: No prompt provided" >&2
    echo "Try: Include a 'prompt' field in the JSON input." >&2
    exit 1
  fi

  if [[ -z "$VERIFICATION_CRITERIA" ]] || [[ "$VERIFICATION_CRITERIA" == "null" ]]; then
    echo "Error: --verification-criteria is required" >&2
    echo "Try: Include a 'verification_criteria' field in the JSON input, or pass --verification-criteria on the command line." >&2
    exit 1
  fi
else
  # Legacy: parse arguments directly from positional params
  PROMPT_PARTS=()
  MAX_ITERATIONS=0
  VERIFICATION_CRITERIA=""
  TEST_COMMAND=""
  VERIFIER_MODEL="opus"
  PLAN_MODE="false"
  TASK_ID=""
  TASK_JSON=""
  TASK_PROMPT_CONTENT=""
  SESSION_DIR=".claude"

  while [[ $# -gt 0 ]]; do
    case $1 in
      -h|--help)
        cat << 'HELP_EOF'
GSD-VGL - Verifier-Gated Loop with TDD + opencode MCP

USAGE:
  /bridge [PROMPT...] [OPTIONS]

ARGUMENTS:
  PROMPT...    Task description (can be multiple words)

OPTIONS:
  --verification-criteria '<text>'  What the Verifier checks (REQUIRED)
  --test-command '<cmd>'            Command to run tests (default: auto-detect)
  --verifier-model <model>          Model for Verifier (default: opus)
  --max-iterations <n>              Max iterations (default: unlimited)
  -h, --help                        Show this help

SECURITY MODEL:
  The completion token is NEVER given to the Verifier upfront.

  Instead:
  1. Verifier does its quality checks (reads code, looks for issues)
  2. When Verifier thinks everything is good, it calls fetch-completion-token.sh
  3. That script runs tests INDEPENDENTLY
  4. Token is ONLY revealed if tests pass

HELP_EOF
        exit 0
        ;;
      --max-iterations)
        if [[ -z "${2:-}" ]] || ! [[ "$2" =~ ^[0-9]+$ ]]; then
          echo "Error: --max-iterations requires a positive integer" >&2
          echo "Try: Use --max-iterations 5 (or another positive number)." >&2
          exit 1
        fi
        MAX_ITERATIONS="$2"
        shift 2
        ;;
      --verification-criteria)
        if [[ -z "${2:-}" ]]; then
          echo "Error: --verification-criteria requires text argument" >&2
          echo "Try: Use --verification-criteria 'describe what to verify'." >&2
          exit 1
        fi
        VERIFICATION_CRITERIA="$2"
        shift 2
        ;;
      --test-command)
        if [[ -z "${2:-}" ]]; then
          echo "Error: --test-command requires a command" >&2
          echo "Try: Use --test-command 'pytest' or --test-command 'npm test'." >&2
          exit 1
        fi
        TEST_COMMAND="$2"
        shift 2
        ;;
      --verifier-model)
        if [[ -z "${2:-}" ]]; then
          echo "Error: --verifier-model requires a model name" >&2
          echo "Try: Use --verifier-model opus or --verifier-model sonnet." >&2
          exit 1
        fi
        VERIFIER_MODEL="$2"
        shift 2
        ;;
      *)
        PROMPT_PARTS+=("$1")
        shift
        ;;
    esac
  done

  PROMPT="${PROMPT_PARTS[*]}"

  if [[ -z "$PROMPT" ]]; then
    echo "Error: No prompt provided" >&2
    echo "Try: Pass a prompt as positional arguments, e.g.: /bridge 'Implement feature X'." >&2
    exit 1
  fi

  if [[ -z "$VERIFICATION_CRITERIA" ]]; then
    echo "Error: --verification-criteria is required" >&2
    echo "Try: Add --verification-criteria 'describe what the verifier should check'." >&2
    exit 1
  fi
fi

# Auto-detect test command
if [[ -z "$TEST_COMMAND" ]]; then
  if [[ -f "pyproject.toml" ]] || [[ -f "pytest.ini" ]]; then
    TEST_COMMAND="pytest"
  elif [[ -f "vitest.config.ts" ]] || [[ -f "vitest.config.js" ]]; then
    TEST_COMMAND="bunx vitest run"
  elif [[ -f "package.json" ]]; then
    TEST_COMMAND="npm test"
  else
    TEST_COMMAND="pytest"
  fi
  echo "Auto-detected test command: $TEST_COMMAND"
fi

# Generate cryptographic completion token (128-bit)
COMPLETION_TOKEN="VGL_COMPLETE_$(openssl rand -hex 16 2>/dev/null || head -c 32 /dev/urandom | xxd -p | tr -d '\n')"
SESSION_ID="vgl_$(date +%s)_$(openssl rand -hex 4 2>/dev/null || head -c 8 /dev/urandom | xxd -p | tr -d '\n')"

# Create state directory
mkdir -p "$SESSION_DIR"

# Store token AND test command in SECRET FILE (tamper-proof)
TEST_CMD_B64=$(echo -n "$TEST_COMMAND" | base64 -w0)
TEST_CMD_HASH=$(echo -n "$TEST_COMMAND" | sha256sum | cut -d' ' -f1)
cat > "${SESSION_DIR}/verifier-token.secret" <<SECRETEOF
$COMPLETION_TOKEN
TEST_CMD_B64:$TEST_CMD_B64
TEST_CMD_HASH:$TEST_CMD_HASH
SECRETEOF
chmod 600 "${SESSION_DIR}/verifier-token.secret" 2>/dev/null || true

# Generate test assessor token (separate from verifier token)
TQG_TOKEN="TQG_PASS_$(openssl rand -hex 16 2>/dev/null || head -c 32 /dev/urandom | xxd -p | tr -d '\n')"
echo "$TQG_TOKEN" > "${SESSION_DIR}/test-assessor-token.secret"
chmod 600 "${SESSION_DIR}/test-assessor-token.secret" 2>/dev/null || true

# Create state file
PLAN_MODE_FRONTMATTER=""
if [[ "$PLAN_MODE" == "true" ]] && [[ -n "$TASK_ID" ]]; then
  PLAN_MODE_FRONTMATTER="plan_mode: true
task_id: \"$TASK_ID\""
fi

cat > "${SESSION_DIR}/verifier-loop.local.md" <<EOF
---
active: true
session_id: "$SESSION_ID"
iteration: 1
max_iterations: $MAX_ITERATIONS
verification_criteria: |
$(echo "$VERIFICATION_CRITERIA" | sed 's/^/  /')
test_command: "$TEST_COMMAND"
verifier_model: "$VERIFIER_MODEL"
project_dir: "$(pwd)"
started_at: "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
$PLAN_MODE_FRONTMATTER
---

$PROMPT
EOF

# Resolve absolute paths at setup time (subagents don't have CLAUDE_PLUGIN_ROOT)
FETCH_SCRIPT="$PLUGIN_ROOT/scripts/fetch-completion-token.sh"
PROJECT_DIR="$(pwd)"

# Create Verifier prompt — plan mode uses generate-verifier-prompt.sh
if [[ "$PLAN_MODE" == "true" ]] && [[ -n "$TASK_JSON" ]]; then
  PLAN_FILE=".claude/plan/plan.yaml"

  # Use generate-verifier-prompt.sh for immutable prompt generation
  GEN_ARGS=(
    --task-json "$TASK_JSON"
    --fetch-script "$FETCH_SCRIPT"
    --session-dir "$SESSION_DIR"
    --project-dir "$PROJECT_DIR"
  )
  if [[ -f "$PLAN_FILE" ]]; then
    GEN_ARGS+=(--plan-file "$PLAN_FILE")
  fi
  if [[ -n "$TASK_PROMPT_CONTENT" ]]; then
    GEN_ARGS+=(--task-prompt-content "$TASK_PROMPT_CONTENT")
  fi

  bash "${PLUGIN_ROOT}/scripts/generate-verifier-prompt.sh" "${GEN_ARGS[@]}"

  # Also generate test assessor prompt for the tester agent
  ASSESSOR_ARGS=(
    --task-json "$TASK_JSON"
    --session-dir "$SESSION_DIR"
    --project-dir "$PROJECT_DIR"
  )
  if [[ -f "$PLAN_FILE" ]]; then
    ASSESSOR_ARGS+=(--plan-file "$PLAN_FILE")
  fi
  if [[ -n "$TASK_PROMPT_CONTENT" ]]; then
    ASSESSOR_ARGS+=(--task-prompt-content "$TASK_PROMPT_CONTENT")
  fi

  bash "${PLUGIN_ROOT}/scripts/generate-test-assessor-prompt.sh" "${ASSESSOR_ARGS[@]}"

else
  # Standard (non-plan) verifier prompt
  cat > "${SESSION_DIR}/verifier-prompt.local.md" <<EOF
You are a SENIOR CODE REVIEWER performing a production-readiness audit. You are the last line of defense before code ships. Your job is to catch everything that a lazy, rushed, or incompetent implementation would try to sneak past.

You are a bullshit detector. Assume the implementation is guilty until proven innocent.

MINDSET: Imagine a senior engineer at a top company reviewing a PR from a junior. They are looking at this code knowing it will run in production, handle real users, and their name is on the approval. Would they approve this? If they would be embarrassed to have their name on the approval — it's a FAIL.

VERIFICATION CRITERIA:
$VERIFICATION_CRITERIA

═══════════════════════════════════════════════════════════════
STEP 1: DEEP CODE INSPECTION ($PROJECT_DIR/)
═══════════════════════════════════════════════════════════════

Read EVERY relevant source file. For each, check for:

HARD FAILS (any one of these = instant FAIL):
- Functions that are declared but do nothing (empty bodies, pass, return None/null/undefined)
- Hardcoded return values where real logic should be (return True, return [], return {})
- Console.log / print used as the actual implementation
- TODO, FIXME, XXX, HACK, STUB comments indicating unfinished work
- Commented-out code blocks (dead code)
- Error handling that swallows exceptions silently (catch {} / except: pass)
- Functions that always return the same thing regardless of input
- "Mock" or "fake" or "dummy" data used as the real implementation
- Type casts to paper over actual type errors (as any, type: ignore)
- Missing imports that would crash at runtime
- SQL/queries built with string concatenation (injection risk)
- Secrets or API keys hardcoded in source
- File or network operations with no error handling

SMELL CHECKS (multiple smells = FAIL):
- Functions over 100 lines with no decomposition
- 4+ levels of nested conditionals
- Variables named temp, data, result, x with no context
- Magic numbers/strings with no constants
- Duplicated logic across files (copy-paste coding)
- API endpoints with no input validation
- Missing edge cases: null inputs, empty arrays, boundary values
- Tests that mock so much they test nothing real
- Tests with no meaningful assertions

═══════════════════════════════════════════════════════════════
STEP 2: RUN TESTS
═══════════════════════════════════════════════════════════════

cd $PROJECT_DIR && $TEST_COMMAND

If tests fail, stop — FAIL.

If tests pass, check: are these tests actually testing anything? Grep test files for trivial assertions.

═══════════════════════════════════════════════════════════════
STEP 3: VERDICT
═══════════════════════════════════════════════════════════════

Only if ALL of these are true:
- Zero hard fails from Step 1
- No more than 2 minor smells
- Tests pass AND test quality is acceptable
- Verification criteria are genuinely met (not just technically satisfied)
- You would stake your professional reputation on this code

Then run: cd $PROJECT_DIR && bash $FETCH_SCRIPT --session-dir ${SESSION_DIR}

OUTPUT: your entire response is one of:
<verification-complete>
PASS: [paste the token from the fetch script here]
</verification-complete>
or
<verification-complete>
FAIL
[List every issue. Be specific: file path, line, what's wrong, why it matters.]
</verification-complete>

If you FAIL, the issues list is critical — the executor needs to know exactly what to fix.
EOF
fi

# Output setup message
cat <<EOF

╔═══════════════════════════════════════════════════════════════════════════════════════╗
║                     GSD-VGL: VERIFIER-GATED LOOP ACTIVATED                           ║
╠═══════════════════════════════════════════════════════════════════════════════════════╣
║                                                                                       ║
║  Session:              $SESSION_ID
║  Iteration:            1
║  Max iterations:       $(printf "%-10s" "$(if [[ $MAX_ITERATIONS -gt 0 ]]; then echo $MAX_ITERATIONS; else echo "unlimited"; fi)")
║  Test command:         $TEST_COMMAND
║  Verifier model:       $VERIFIER_MODEL
║                                                                                       ║
╠═══════════════════════════════════════════════════════════════════════════════════════╣
║  SECURITY: Token in ${SESSION_DIR}/verifier-token.secret (protected)                  ║
║  Verifier must call fetch-completion-token.sh — tests run independently               ║
╚═══════════════════════════════════════════════════════════════════════════════════════╝

EOF

echo "$PROMPT"
echo ""
echo "═══════════════════════════════════════════════════════════════════════════════════════"
echo "BEGIN WORK — TDD-first: write tests, spawn opencode agents, then verify"
echo "═══════════════════════════════════════════════════════════════════════════════════════"
